build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
labels:
  org.opencontainers.image.title: "Signal API Receiver"
  org.opencontainers.image.description: "HTTP polling bridge for a signal-cli-rest-api json-rpc websocket"
  org.opencontainers.image.source: "https://github.com/kalbasit/signal-api-receiver"
  org.opencontainers.image.licenses: "MIT"
